---
title: "food_sustanibility"
author: "Declan Oberlies"
date: '`r Sys.Date()`'
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
# load packeges ----
library(ggplot2)
library(dplyr)
library(readr)
library(leaflet)
library(patchwork)
library(tidyr)
library(purrr)
```

```{r}
url <- 'https://ourworldindata.org/explorers/global-food.csv?v=1&csvType=full&useColumnShortNames=true&Food=Maize+%28corn%29&Metric=Production&Per+Capita=false&Per+capita=false?'
`%not_in%` <- negate(`%in%`)
food_producers <- read_csv(url) %>%
  filter(entity %not_in% c("World",
                           "North America",
                           "South America",
                           "Africa",
                           "Asia",
                           "Ociana",
                           "Europe"),
         !grepl("\\(FAO\\)$", entity)) %>%
  group_by(entity)
#View(food_producers)
food_producers %>%
  pull(entity) %>%
  unique()

fp_2023 <- food_producers %>%
  filter(year == 2023)

  ggplot(food_producers,
       aes(x = entity,
           y = maize__00000056__production__005510__tonnes)
       ) +
  geom_col()


```

